### ISSUE TITLE
cannot npm install project

### ISSUE THREAD

**Issue by craigElevate** [creativetimofficial/ct-vision-ui-dashboard-pro-chakra#1]
### Version
1.0.0
### Reproduction link
https://github.com/craigElevate/vision-ui-test
### Operating System
mac os
### Device
macbook pro
### Browser & Version
chrome
### Steps to reproduce
I cannot npm instal the project.
1. Trying npm install with dependancies as is fails because there are many dependancies that need a version of react that is 16 and under. Removing these dependancies removes a lot of the functionality I need that this project should provide me
2. Taking react back to version 16.x.x brings up an error where there is problem with node-sass
### What is expected?
To be able to npm install and run the project
### What is actually happening?
Cannot install the project

---
### Solution
need to either downgrade to react 16 as 17 does not add any additional benefits other than future upgrades, or ensure that all current dependancies work with react 17 and swap out the ones that do not.

### Additional comments
I am using the latest stable version of node (16.14.0)
Other related dependancies on my system are up to date

**Comment by simmmpleweb** [comment]
Hello, @craigElevate ! Thanks for using our products. Right now we're solving this problems, for the moment you can try using `npm --legacy-peer-deps install` or `npm --force install`. Regards, Vlad.

**Comment by simmmpleweb** [comment]
We just uploaded our changes ! The problems above should be solved.
