### ISSUE TITLE
[Feature Request] can we get version with typescript

### ISSUE THREAD

**Issue by MishanthSpacce** [creativetimofficial/ct-vision-ui-dashboard-pro-chakra#3]
### What is your enhancement?
is it possible to get a version with transcript of the design we bought.

**Comment by simmmpleweb** [comment]
Hello, @MishanthSpacce ! Thank you for your proposal! Unfortunately, we do not have a Typescript version planned, but if we decide to go forward with the idea we will ping you here.
Best regards, Vlad.
